# Generated by Django 5.2.3 on 2025-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
