# Generated by Django 5.2.3 on 2025-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedprojects',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
