# Generated by Django 5.2.3 on 2025-09-22 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course_project_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('project_category', models.CharField(choices=[('ml', 'Machine learning'), ('web', 'Web Development'), ('mobile', 'Mobile app'), ('design', 'UI/UX Design'), ('other', 'Others')], max_length=50)),
                ('project_description', models.TextField()),
                ('Technologies', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=100)),
                ('deadline', models.DateTimeField()),
                ('contact_infor', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
