# Generated by Django 5.2.3 on 2025-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customprojects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customprojects',
            old_name='contact_infor',
            new_name='contact_info',
        ),
        migrations.AlterField(
            model_name='customprojects',
            name='project_category',
            field=models.CharField(max_length=50),
        ),
    ]
