# Generated by Django 5.2.3 on 2025-09-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_contact_infor_customprojects_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customprojects',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectcategory'),
        ),
    ]
