# Generated by Django 5.2.3 on 2025-09-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_projectcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprojects',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectcategory'),
        ),
    ]
