# Generated by Django 5.2.3 on 2025-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customprojects_deadline_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='trying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
