# Generated by Django 5.2.3 on 2025-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_trying'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImage1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projectimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImage2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projectimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImage3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projectimages/'),
        ),
    ]
