# Generated by Django 5.2.3 on 2025-09-23 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_project_demo_link_project_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploade_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
