# Generated by Django 5.2.3 on 2025-09-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_project_uploade_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uploade_by',
            new_name='uploaded_by',
        ),
    ]
