# Generated by Django 5.2.3 on 2025-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_project_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprojects',
            name='Technologies',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
