# Generated by Django 5.2.3 on 2025-09-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customprojects_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('bought', 'Bought')], default='pending', max_length=20),
        ),
    ]
