# Generated by Django 5.2.3 on 2025-09-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('bought', 'Bought'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
