# Generated by Django 5.2.3 on 2025-09-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agreement',
            field=models.BooleanField(default=True),
        ),
    ]
