# Generated by Django 5.2.3 on 2025-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_project_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
