# Generated by Django 5.2.3 on 2025-09-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_project_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement',
            field=models.BooleanField(default=True),
        ),
    ]
