# Generated by Django 5.2.3 on 2025-09-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_project_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
