# Generated by Django 5.2.3 on 2025-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_project_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
