# Generated by Django 5.2.3 on 2025-09-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='bought_by',
        ),
    ]
