# Generated by Django 5.2.3 on 2025-09-28 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_user_payment_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bought_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.project'),
        ),
    ]
