# Generated by Django 5.2.3 on 2025-09-28 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_payment_bought_by_alter_payment_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadedprojects',
            options={'verbose_name': 'Downlaoded Project'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
