# Generated by Django 5.2.3 on 2025-09-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_downloadedprojects_options_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementInfo', models.CharField(max_length=100)),
            ],
        ),
    ]
