# Generated by Django 5.2.3 on 2025-09-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
