# Generated by Django 5.2.3 on 2025-10-05 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedprojects',
            name='downloaders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
